@file:Suppress("unused", "PackageDirectoryMismatch")

package androidx.compose.material.icons.rounded

import androidx.compose.material.icons.Icons
import androidx.compose.ui.graphics.vector.ImageVector

val Icons.Rounded.Add: ImageVector get() = ImageVector("Rounded.Add")
val Icons.Rounded.Album: ImageVector get() = ImageVector("Rounded.Album")
val Icons.Rounded.Block: ImageVector get() = ImageVector("Rounded.Block")
val Icons.Rounded.Bolt: ImageVector get() = ImageVector("Rounded.Bolt")
val Icons.Rounded.Check: ImageVector get() = ImageVector("Rounded.Check")
val Icons.Rounded.CheckCircle: ImageVector get() = ImageVector("Rounded.CheckCircle")
val Icons.Rounded.Close: ImageVector get() = ImageVector("Rounded.Close")
val Icons.Rounded.Delete: ImageVector get() = ImageVector("Rounded.Delete")
val Icons.Rounded.DeleteSweep: ImageVector get() = ImageVector("Rounded.DeleteSweep")
val Icons.Rounded.DragHandle: ImageVector get() = ImageVector("Rounded.DragHandle")
val Icons.Rounded.ErrorOutline: ImageVector get() = ImageVector("Rounded.ErrorOutline")
val Icons.Rounded.ExpandMore: ImageVector get() = ImageVector("Rounded.ExpandMore")
val Icons.Rounded.Folder: ImageVector get() = ImageVector("Rounded.Folder")
val Icons.Rounded.GraphicEq: ImageVector get() = ImageVector("Rounded.GraphicEq")
val Icons.Rounded.HelpOutline: ImageVector get() = ImageVector("Rounded.HelpOutline")
val Icons.Rounded.History: ImageVector get() = ImageVector("Rounded.History")
val Icons.Rounded.Home: ImageVector get() = ImageVector("Rounded.Home")
val Icons.Rounded.HourglassTop: ImageVector get() = ImageVector("Rounded.HourglassTop")
val Icons.Rounded.Info: ImageVector get() = ImageVector("Rounded.Info")
val Icons.Rounded.LibraryMusic: ImageVector get() = ImageVector("Rounded.LibraryMusic")
val Icons.Rounded.MoreVert: ImageVector get() = ImageVector("Rounded.MoreVert")
val Icons.Rounded.MusicNote: ImageVector get() = ImageVector("Rounded.MusicNote")
val Icons.Rounded.NewReleases: ImageVector get() = ImageVector("Rounded.NewReleases")
val Icons.Rounded.Palette: ImageVector get() = ImageVector("Rounded.Palette")
val Icons.Rounded.Pause: ImageVector get() = ImageVector("Rounded.Pause")
val Icons.Rounded.Person: ImageVector get() = ImageVector("Rounded.Person")
val Icons.Rounded.PlayArrow: ImageVector get() = ImageVector("Rounded.PlayArrow")
val Icons.Rounded.PushPin: ImageVector get() = ImageVector("Rounded.PushPin")
val Icons.Rounded.QueueMusic: ImageVector get() = ImageVector("Rounded.QueueMusic")
val Icons.Rounded.Refresh: ImageVector get() = ImageVector("Rounded.Refresh")
val Icons.Rounded.Repeat: ImageVector get() = ImageVector("Rounded.Repeat")
val Icons.Rounded.RepeatOne: ImageVector get() = ImageVector("Rounded.RepeatOne")
val Icons.Rounded.Schedule: ImageVector get() = ImageVector("Rounded.Schedule")
val Icons.Rounded.Science: ImageVector get() = ImageVector("Rounded.Science")
val Icons.Rounded.Search: ImageVector get() = ImageVector("Rounded.Search")
val Icons.Rounded.Settings: ImageVector get() = ImageVector("Rounded.Settings")
val Icons.Rounded.Share: ImageVector get() = ImageVector("Rounded.Share")
val Icons.Rounded.Shuffle: ImageVector get() = ImageVector("Rounded.Shuffle")
val Icons.Rounded.SkipNext: ImageVector get() = ImageVector("Rounded.SkipNext")
val Icons.Rounded.SkipPrevious: ImageVector get() = ImageVector("Rounded.SkipPrevious")
val Icons.Rounded.Sort: ImageVector get() = ImageVector("Rounded.Sort")
val Icons.Rounded.Stop: ImageVector get() = ImageVector("Rounded.Stop")
val Icons.Rounded.SwapHoriz: ImageVector get() = ImageVector("Rounded.SwapHoriz")
val Icons.Rounded.SwapVert: ImageVector get() = ImageVector("Rounded.SwapVert")
val Icons.Rounded.Tag: ImageVector get() = ImageVector("Rounded.Tag")
val Icons.Rounded.ThumbDown: ImageVector get() = ImageVector("Rounded.ThumbDown")
val Icons.Rounded.ThumbUp: ImageVector get() = ImageVector("Rounded.ThumbUp")
val Icons.Rounded.TrendingUp: ImageVector get() = ImageVector("Rounded.TrendingUp")
val Icons.Rounded.Tune: ImageVector get() = ImageVector("Rounded.Tune")
