#!/usr/bin/env bash
#
# Offline type-check for the :app module.
#
# Runs the Kotlin 2.1.20 compiler directly (no Gradle, no Android SDK) over the app sources
# with the REAL compiled engine classes on the classpath plus the hand-written platform stubs
# in app/src/typecheck-stubs/. See app/src/typecheck-stubs/README.md for what this does and
# does not prove.
#
# Usage:
#   app/typecheck.sh          # core packages (data, data.db, data.prefs, di, playback, test) -- must be clean
#   app/typecheck.sh ui       # core + ui/** + MainActivity/MuiscApplication (best effort, Compose is stubbed)
#   app/typecheck.sh all      # alias for `ui`
#
set -u

MODE="${1:-core}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
APP="$HERE"
STUBS="$APP/src/typecheck-stubs"
ENG="$ROOT/engine"
OUT="${TYPECHECK_OUT:-${TMPDIR:-/tmp}/muisc-typecheck}"
GEN="$OUT/generated"
M2="${GRADLE_USER_HOME:-$HOME/.gradle}/caches/modules-2/files-2.1"

jar_for() { find "$M2/$1" -name "$2" 2>/dev/null | sort | tail -1; }

KC="$(jar_for org.jetbrains.kotlin/kotlin-compiler-embeddable 'kotlin-compiler-embeddable-*.jar')"
STDLIB="$(jar_for org.jetbrains.kotlin/kotlin-stdlib 'kotlin-stdlib-2*.jar')"
COROUTINES="$(jar_for org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm 'kotlinx-coroutines-core-jvm-*.jar')"
SERCORE="$(jar_for org.jetbrains.kotlinx/kotlinx-serialization-core-jvm 'kotlinx-serialization-core-jvm-*.jar')"
SERJSON="$(jar_for org.jetbrains.kotlinx/kotlinx-serialization-json-jvm 'kotlinx-serialization-json-jvm-*.jar')"
ANNO="$(jar_for org.jetbrains/annotations 'annotations-*.jar')"
TROVE="$(jar_for org.jetbrains.intellij.deps/trove4j 'trove4j-*.jar')"
KTEST="$(jar_for org.jetbrains.kotlin/kotlin-test 'kotlin-test-2*.jar')"
KTESTJ5="$(jar_for org.jetbrains.kotlin/kotlin-test-junit5 'kotlin-test-junit5-*.jar')"
JUPITER_API="$(jar_for org.junit.jupiter/junit-jupiter-api 'junit-jupiter-api-*.jar')"

for v in KC STDLIB COROUTINES SERCORE SERJSON; do
  if [ -z "${!v}" ]; then
    echo "typecheck.sh: could not find the jar for \$$v under $M2" >&2
    echo "  Run './gradlew :engine:player:compileKotlin' once so Gradle populates the module cache." >&2
    exit 2
  fi
done

CP="$STDLIB:$COROUTINES:$SERCORE:$SERJSON:$ANNO:$KTEST:$KTESTJ5:$JUPITER_API"
missing_engine=0
for m in audio dsp analysis transitions metrics player; do
  d="$ENG/$m/build/classes/kotlin/main"
  [ -d "$d" ] || { echo "typecheck.sh: missing engine classes: $d" >&2; missing_engine=1; }
  CP="$CP:$d"
done
if [ "$missing_engine" = 1 ]; then
  echo "  Run './gradlew :engine:audio:compileKotlin :engine:dsp:compileKotlin :engine:analysis:compileKotlin \\" >&2
  echo "       :engine:transitions:compileKotlin :engine:metrics:compileKotlin :engine:player:compileKotlin'" >&2
  exit 2
fi

# ---------------------------------------------------------------------------
# Generate dev.muisc.app.R from the real res/ files, so that every R.string /
# R.drawable reference in the sources is checked against the actual resources.
# ---------------------------------------------------------------------------
rm -rf "$OUT"
mkdir -p "$GEN"
{
  echo '@file:Suppress("unused", "ClassName", "ObjectPropertyName")'
  echo
  echo 'package dev.muisc.app'
  echo
  echo '/** Generated by app/typecheck.sh from app/src/main/res -- mirrors what aapt2 would produce. */'
  echo 'object R {'
  echo '    object string {'
  grep -ho '<string name="[^"]*"' "$APP/src/main/res/values/"*.xml 2>/dev/null |
    sed 's/.*name="//; s/"//' | sort -u | awk '{print "        const val " $0 ": Int = " (2131034112 + NR)}'
  echo '    }'
  echo '    object plurals {'
  grep -ho '<plurals name="[^"]*"' "$APP/src/main/res/values/"*.xml 2>/dev/null |
    sed 's/.*name="//; s/"//' | sort -u | awk '{print "        const val " $0 ": Int = " (2131099648 + NR)}'
  echo '    }'
  echo '    object drawable {'
  ls "$APP/src/main/res/drawable"* 2>/dev/null | sed 's/\.[a-z]*$//' | grep -v ':' | grep -v '^$' |
    sort -u | awk 'NF {print "        const val " $0 ": Int = " (2130903040 + NR)}'
  echo '    }'
  echo '    object mipmap {'
  ls "$APP/src/main/res/mipmap"* 2>/dev/null | sed 's/\.[a-z]*$//' | grep -v ':' | grep -v '^$' |
    sort -u | awk 'NF {print "        const val " $0 ": Int = " (2130968576 + NR)}'
  echo '    }'
  echo '    object color {'
  grep -ho '<color name="[^"]*"' "$APP/src/main/res/values/"*.xml 2>/dev/null |
    sed 's/.*name="//; s/"//' | sort -u | awk '{print "        const val " $0 ": Int = " (2130771968 + NR)}'
  echo '    }'
  echo '    object style {'
  grep -ho '<style name="[^"]*"' "$APP/src/main/res/values/"*.xml 2>/dev/null |
    sed 's/.*name="//; s/"//' | tr '.' '_' | sort -u | awk '{print "        const val " $0 ": Int = " (2131165184 + NR)}'
  echo '    }'
  echo '}'
} > "$GEN/R.kt"

K="$APP/src/main/kotlin/dev/muisc/app"
SRC="$STUBS $GEN"
SRC="$SRC $K/data $K/di $K/playback"
SRC="$SRC $APP/src/test/kotlin"

if [ "$MODE" = "ui" ] || [ "$MODE" = "all" ]; then
  SRC="$SRC $K/ui $K/MainActivity.kt $K/MuiscApplication.kt"
fi

mkdir -p "$OUT/classes"
java -Xmx2g -cp "$KC:$STDLIB:$ANNO:$COROUTINES:$TROVE" org.jetbrains.kotlin.cli.jvm.K2JVMCompiler \
  -no-stdlib -nowarn -jvm-target 17 \
  -opt-in=kotlin.RequiresOptIn \
  -classpath "$CP" \
  -d "$OUT/classes" \
  $SRC 2>&1 |
  grep -v '^warning:' |
  grep -v 'JAVA_TOOL_OPTIONS' |
  grep -v '^info:'

status=${PIPESTATUS[0]}
echo
if [ "$status" = 0 ]; then
  echo "typecheck.sh [$MODE]: OK"
else
  echo "typecheck.sh [$MODE]: FAILED"
fi
exit "$status"
